### ISSUE TITLE
long output file names can cause an issue in some situations

### ISSUE THREAD

**Issue by CWempe** [wader/inkmake#8]
Following up on my second issue I mentioned [here](https://github.com/wader/inkmake/issues/7):

It looks like long output file names can cause an issue in some situations.

At first it looked like reducing the output filename to `aaaaaaaaaaaaaaaa.png` was necessary to work around this issue.  
But then I discovered the longer file name workes if there is a working line above it. 🤔 

# Working

**inkfile**

```
aaaaaaaaaaaaaaaa.png test.svg
aaaaaaaaaaaaaaaaa.png test.svg
```

**command** (might be a little over complicated)

```powershell
c:\tools\ruby30\bin\inkmake.bat -s C:\Users\cwempe\Documents\temp\exported\ -o C:\Users\cwempe\Documents\temp\exported\ --inkscape "C:\Program Files\Inkscape\bin\inkscape.exe" C:\Users\cwempe\Documents\temp\exported\exported\dark_white_light\inkfile1 --verbose
```

**output**

```
2>
** (org.inkscape.Inkscape:74504): WARNING **: 01:56:05.054: Fonts dir 'C:\Users\cwempe\AppData\Roaming\inkscape\fonts' does not exist and will be ignored.
2> Inkscape interactive shell mode. Type 'action-list' to list all actions. Type 'quit' to quit.
2>  Input of the form:
2>  action1:arg1; action2:arg2; verb1; verb2; ...
2> Only verbs that don't require a desktop may be used.
1> >
< file-open:C:/Users/cwempe/Documents/temp/exported/test.svg
2> file-open:C:/Users/cwempe/Documents/temp/exported/test.svg
< export-type:png
1> >
< export-filename:C:/Users/cwempe/Documents/temp/exported/aaaaaaaaaaaaaaaa.png
2> export-type:png
< export-width:100
1> >
< export-height:100
2> export-filename:C:/Users/cwempe/Documents/temp/exported/aaaaaaaaaaaaaaaa.png
< export-area:
1> >
< export-area-drawing:false
2> export-width:100
< export-id:
1> >
< export-area-page:false
2> export-height:100
< export-area-page:true
1> >
< export-do:
2> export-area:
1> >
< file-close:
2> export-area-drawing:false
aaaaaaaaaaaaaaaa.png 0x0
< file-open:C:/Users/cwempe/Documents/temp/exported/test.svg
1> >
< export-type:png
2> export-id:
< export-filename:C:/Users/cwempe/Documents/temp/exported/aaaaaaaaaaaaaaaaa.png
1> >
< export-width:100
2> export-area-page:false
< export-height:100
1> >
< export-area:
2> export-area-page:true
< export-area-drawing:false
1> >
< export-id:
2> export-do:
< export-area-page:false
2> Background RRGGBBAA: ffffff00
< export-area-page:true
2> Area 0:0:100:100 exported to 100 x 100 pixels (96 dpi)
< export-do:
1> >
< file-close:
2> file-close:
aaaaaaaaaaaaaaaaa.png 0x0
```

# NOT Working

**inkfile**

```
aaaaaaaaaaaaaaaaa.png test.svg
aaaaaaaaaaaaaaaa.png test.svg
```

**command** (might be a little over complicated)

_same as above_

**output**

```
2>
** (org.inkscape.Inkscape:73932): WARNING **: 01:57:02.361: Fonts dir 'C:\Users\cwempe\AppData\Roaming\inkscape\fonts' does not exist and will be ignored.
2> Inkscape interactive shell mode. Type 'action-list' to list all actions. Type 'quit' to quit.
2>  Input of the form:
2>  action1:arg1; action2:arg2; verb1; verb2; ...
2> Only verbs that don't require a desktop may be used.
1> >
< file-open:C:/Users/cwempe/Documents/temp/exported/test.svg
2> file-open:C:/Users/cwempe/Documents/temp/exported/test.svg
< export-type:png
1> >
< export-filename:C:/Users/cwempe/Documents/temp/exported/aaaaaaaaaaaaaaaaa.png
2> export-type:png
< export-width:100
1> >
< export-height:100
2> export-filename:C:/Users/cwempe/Documents/temp/exported/aaaaaaaaaaaaaaaaa.pn
< export-area:
C:/tools/ruby30/lib/ruby/gems/3.0.0/gems/inkmake-0.1.5/lib/inkmake.rb:185:in `read': byte oriented read for character buffered IO (IOError)
        from C:/tools/ruby30/lib/ruby/gems/3.0.0/gems/inkmake-0.1.5/lib/inkmake.rb:185:in `response'
        from C:/tools/ruby30/lib/ruby/gems/3.0.0/gems/inkmake-0.1.5/lib/inkmake.rb:281:in `block in export1'
        from C:/tools/ruby30/lib/ruby/gems/3.0.0/gems/inkmake-0.1.5/lib/inkmake.rb:279:in `each'
        from C:/tools/ruby30/lib/ruby/gems/3.0.0/gems/inkmake-0.1.5/lib/inkmake.rb:279:in `export1'
        from C:/tools/ruby30/lib/ruby/gems/3.0.0/gems/inkmake-0.1.5/lib/inkmake.rb:304:in `export'
        from C:/tools/ruby30/lib/ruby/gems/3.0.0/gems/inkmake-0.1.5/lib/inkmake.rb:638:in `block (2 levels) in process'
        from C:/tools/ruby30/lib/ruby/gems/3.0.0/gems/inkmake-0.1.5/lib/inkmake.rb:589:in `each'
        from C:/tools/ruby30/lib/ruby/gems/3.0.0/gems/inkmake-0.1.5/lib/inkmake.rb:589:in `block in process'
        from C:/tools/ruby30/lib/ruby/gems/3.0.0/gems/inkmake-0.1.5/lib/inkmake.rb:121:in `initialize'
        from C:/tools/ruby30/lib/ruby/gems/3.0.0/gems/inkmake-0.1.5/lib/inkmake.rb:588:in `new'
        from C:/tools/ruby30/lib/ruby/gems/3.0.0/gems/inkmake-0.1.5/lib/inkmake.rb:588:in `process'
        from C:/tools/ruby30/lib/ruby/gems/3.0.0/gems/inkmake-0.1.5/lib/inkmake.rb:830:in `run'
        from C:/tools/ruby30/lib/ruby/gems/3.0.0/gems/inkmake-0.1.5/bin/inkmake:3:in `<top (required)>'
        from C:/tools/ruby30/bin/inkmake:25:in `load'
        from C:/tools/ruby30/bin/inkmake:25:in `<main>'
```

**Comment by wader** [comment]
Hello, that is strange, seems to work fine on macOS, even with very long filenames. I would guess we hit some size limit somewhere, either in inkscape readline or maybe in ruby csv parser. What version of inkscape and ruby do you use?

**Comment by CWempe** [comment]
according to the log:

inkmake: v0.1.5
Inkscape: v1.1 (c68e22c387, 2021-05-23) [latest stable I guess]

ruby: v3.0.0 [according to the inkmake path in the log above]
ruby: v2.6.5p114 (2019-10-01 revision 67812) [x64-mingw32] [according to `ruby --version]

If you cannot reproduce this, never mind.
I am not sure I will need this in the future.
And using a docker container might be the better and more reliable approach in the future anyway. 🤷‍♂️

**Comment by wader** [comment]
Hi, this should be fixed in master now. If it's messy to test i can probably do a release anyway, i managed to reproduce the same issue and this fixed it for me.

**Comment by wader** [comment]
0.1.6 published https://rubygems.org/gems/inkmake/versions/0.1.6 with fixes
